<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11744" started-at="2021-08-20T18:09:55Z" finished-at="2021-08-20T18:10:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11744" started-at="2021-08-20T18:09:55Z" finished-at="2021-08-20T18:10:07Z">
      <class name="com.zohoCRM.tests.SignInTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.zohoCRM.tests.SignInTest@4cf777e8]" name="setup" is-config="true" duration-ms="8538" started-at="2021-08-20T18:09:55Z" finished-at="2021-08-20T18:10:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verify_SignIn()[pri:0, instance:com.zohoCRM.tests.SignInTest@4cf777e8]" name="verify_SignIn" duration-ms="2290" started-at="2021-08-20T18:10:04Z" finished-at="2021-08-20T18:10:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The error message is not proper]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The error message is not proper
at com.zohoCRM.pages.ZohoAccountsLoginPage.verify_ErrorMessage(ZohoAccountsLoginPage.java:111)
at com.zohoCRM.tests.SignInTest.verify_SignIn(SignInTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_SignIn -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.zohoCRM.tests.SignInTest@4cf777e8]" name="tearDown" is-config="true" duration-ms="840" started-at="2021-08-20T18:10:06Z" finished-at="2021-08-20T18:10:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.zohoCRM.tests.SignInTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
